version: '3'

services:
  postgres_db:
    image: postgres:10
    ports:
      - '5432:5432'
    env_file:
      - '.env'
  web:
    build: '.'
    volumes:
      - ./web:/boilerplate
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
    env_file:
      - '.env'
